[package]
name = "zeekoe"
version = "0.1.0"
authors = ["Kenny Foner <kwf@boltlabs.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "zeekoe"
path = "src/lib.rs"

[[bin]]
name = "zeekoe-client"
path = "src/bin/customer/main.rs"

[[bin]]
name = "zeekoe-server"
path = "src/bin/merchant/main.rs"

[features]
allow_explicit_certificate_trust = []

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-rustls = "0.22"
webpki-roots = "0.21"
x509-parser = "0.9"
async-trait = "0.1"
sha2 = "0.9"
digest = "0.9"
generic-array = "0.14"
ring = "0.16"
futures = "0.3"
num = "0.3.1"
bincode = "1.3"
serde = "1"
thiserror = "1"
typenum = "1.12"
zeroize = { version = "1.2", features = ["zeroize_derive"] }
dialectic = { version = "0.4", path = "../dialectic/dialectic", features = ["bincode"] }