[package]
name = "zeekoe"
version = "0.1.0"
authors = ["Kenny Foner"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "zeekoe"
path = "src/lib.rs"

[[bin]]
name = "zeekoe-client"
path = "src/bin/customer/main.rs"

[[bin]]
name = "zeekoe-server"
path = "src/bin/merchant/main.rs"

[dependencies]
tokio = { version = "0.2.22", features = ["full"] }
tonic = "0.3.1"
prost = "0.6"
sha2 = "0.9"
digest = "0.9"
generic-array = "0.14"
ring = "0.16"
futures = "0.3"
num = "0.3.1"
bincode = "1.3"
serde = "1"
thiserror = "1"
typenum = "1.12"
async-trait = "0.1"
dialectic = { path = "../dialectic" }

[build-dependencies]
tonic-build = "0.3.1"