database = { sqlite = "merchant.db" }
tezos_account = "../tezos-contract/pytezos-tests/sample_files/tz1VcYZwxQoyxfjhpNiRkdCUe5rzs53LMev6.json"

[[service]]
address = "::1"
private_key = "localhost.key"
certificate = "localhost.crt"

[[service]]
address = "127.0.0.1"
private_key = "localhost.key"
certificate = "localhost.crt"
