database = { sqlite = "merchant.db" }
tezos_account = "merchant_tezos_key_material.json"

[[service]]
address = "::1"
private_key = "localhost.key"
certificate = "localhost.crt"

[[service]]
address = "127.0.0.1"
private_key = "localhost.key"
certificate = "localhost.crt"
