name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          components: rustfmt, clippy

      - uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.BOLT_CI_SSH_PRIVATEKEY }}

      - name: Install dependencies
        run: sudo apt install libudev-dev

      - name: Format check
        run: cargo fmt -- --check

      - name: Clippy lint
        run: cargo clippy --all-features --all-targets --verbose -- -Dwarnings

      - name: Build
        run: cargo build --all-features --all-targets --verbose

      - name: Run all tests except doctests
        run: cargo test --all-features --all-targets --verbose

      - name: Run all doctests
        run: cargo test --all-features --doc --verbose

      - name: Build documentation
        run: cargo doc --all-features --no-deps --verbose
